"""empty message

Revision ID: 978a11441b45
Revises: 
Create Date: 2022-04-18 11:33:47.546293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978a11441b45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Header', sa.String(length=128), nullable=True),
    sa.Column('Description', sa.String(length=128), nullable=True),
    sa.Column('Create_date', sa.DateTime(), nullable=True),
    sa.Column('Owner', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_model_Header'), 'announcement_model', ['Header'], unique=True)
    op.create_index(op.f('ix_announcement_model_Owner'), 'announcement_model', ['Owner'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcement_model_Owner'), table_name='announcement_model')
    op.drop_index(op.f('ix_announcement_model_Header'), table_name='announcement_model')
    op.drop_table('announcement_model')
    # ### end Alembic commands ###
